### ISSUE TITLE
rdgen failed

### ISSUE THREAD

**Issue by fangyi-zhou** [JetBrains/resharper-rider-plugin#21] opened 2019-10-05 17:32 UTC
```
warning: classpath entry points to a non-existent location: /Users/fangyi/repos/Plugin/build/riderRD-2019.2-SNAPSHOT/lib/rd/rider-model.jar
/Users/fangyi/repos/Plugin/protocol/src/main/kotlin/model/rider/MyPluginModel.kt:3:22: error: unresolved reference: rider
import com.jetbrains.rider.model.nova.ide.SolutionModel
                     ^
/Users/fangyi/repos/Plugin/protocol/src/main/kotlin/model/rider/MyPluginModel.kt:8:31: error: unresolved reference: SolutionModel
object PaketPluginModel : Ext(SolutionModel.Solution) {
                              ^
Compilation finished in 5802 ms
Compilation failed. Return code: 1(COMPILATION_ERROR).
```
I've had a look and there seems to be code to setup the snapshot library in the build dir, could anyone help? Thanks

**Comment by fangyi-zhou** [comment] 2019-10-05 17:39
In particular
https://github.com/JetBrains/resharper-rider-plugin/blob/master/content/build.gradle#L22
I'm not sure where is this directory set up?

**Comment by ForNeVeR** [comment] 2019-10-07 06:37
What command do you use to compile the plugin?

**Comment by Settler** [comment] 2019-10-07 09:50
I have similar problem.
Steps to reproduce:

1. Create new project from template
2. Run configuration to generate protocol

Workaround:
Find specific version of Rider snapshot in gradle cache and copy it to `build` folder.
Should looks like this:
![image](https://user-images.githubusercontent.com/104102/66302014-dc7d9400-e900-11e9-9aac-d4aacc63604a.png)

**Comment by ForNeVeR** [comment] 2020-02-24 13:29
This should be fixed by https://github.com/JetBrains/resharper-rider-plugin/commit/c9cbef1b86d72674fc671a1143455b44121bfe2c.

**Closed by ForNeVeR** 2020-02-24 13:29 UTC
